---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
    volumes:
      - /path/to/data:/config
      - /path/to/movies:/movies #Dossier contenant les films
      - /path/to/downloadclient-downloads:/downloads #Dossier Seedbox
    ports:
      - 7878:7878
    restart: unless-stopped