version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - '/opt/komga:/config'
      - '/media/share/Comics:/data'
    ports:
      - 8585:8080
    user: "1000:1000"
    environment:
      - TZ=America/Montreal
    restart: unless-stopped