---
version: "3.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
    volumes:
      - /opt/nextcloud:/config
      - /mnt/share:/data
    ports:
      - 444:443
    restart: unless-stopped