---
version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/music:/music #Dossier contenant la music
      - /path/to/downloads:/downloads #Dossier Seedbox
    ports:
      - 8686:8686
    restart: unless-stopped